# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/daniel_nasc/codes/cpp/heap

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/daniel_nasc/codes/cpp/heap

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/daniel_nasc/codes/cpp/heap/CMakeFiles /home/daniel_nasc/codes/cpp/heap//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/daniel_nasc/codes/cpp/heap/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named heap_espaconave

# Build rule for target.
heap_espaconave: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 heap_espaconave
.PHONY : heap_espaconave

# fast build rule for target.
heap_espaconave/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/heap_espaconave.dir/build.make CMakeFiles/heap_espaconave.dir/build
.PHONY : heap_espaconave/fast

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

espacoNave.o: espacoNave.cpp.o
.PHONY : espacoNave.o

# target to build an object file
espacoNave.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/heap_espaconave.dir/build.make CMakeFiles/heap_espaconave.dir/espacoNave.cpp.o
.PHONY : espacoNave.cpp.o

espacoNave.i: espacoNave.cpp.i
.PHONY : espacoNave.i

# target to preprocess a source file
espacoNave.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/heap_espaconave.dir/build.make CMakeFiles/heap_espaconave.dir/espacoNave.cpp.i
.PHONY : espacoNave.cpp.i

espacoNave.s: espacoNave.cpp.s
.PHONY : espacoNave.s

# target to generate assembly for a file
espacoNave.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/heap_espaconave.dir/build.make CMakeFiles/heap_espaconave.dir/espacoNave.cpp.s
.PHONY : espacoNave.cpp.s

heap.o: heap.cpp.o
.PHONY : heap.o

# target to build an object file
heap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/heap_espaconave.dir/build.make CMakeFiles/heap_espaconave.dir/heap.cpp.o
.PHONY : heap.cpp.o

heap.i: heap.cpp.i
.PHONY : heap.i

# target to preprocess a source file
heap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/heap_espaconave.dir/build.make CMakeFiles/heap_espaconave.dir/heap.cpp.i
.PHONY : heap.cpp.i

heap.s: heap.cpp.s
.PHONY : heap.s

# target to generate assembly for a file
heap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/heap_espaconave.dir/build.make CMakeFiles/heap_espaconave.dir/heap.cpp.s
.PHONY : heap.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/heap_espaconave.dir/build.make CMakeFiles/heap_espaconave.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/heap_espaconave.dir/build.make CMakeFiles/heap_espaconave.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/heap_espaconave.dir/build.make CMakeFiles/heap_espaconave.dir/main.cpp.s
.PHONY : main.cpp.s

passageiro.o: passageiro.cpp.o
.PHONY : passageiro.o

# target to build an object file
passageiro.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/heap_espaconave.dir/build.make CMakeFiles/heap_espaconave.dir/passageiro.cpp.o
.PHONY : passageiro.cpp.o

passageiro.i: passageiro.cpp.i
.PHONY : passageiro.i

# target to preprocess a source file
passageiro.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/heap_espaconave.dir/build.make CMakeFiles/heap_espaconave.dir/passageiro.cpp.i
.PHONY : passageiro.cpp.i

passageiro.s: passageiro.cpp.s
.PHONY : passageiro.s

# target to generate assembly for a file
passageiro.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/heap_espaconave.dir/build.make CMakeFiles/heap_espaconave.dir/passageiro.cpp.s
.PHONY : passageiro.cpp.s

recurso.o: recurso.cpp.o
.PHONY : recurso.o

# target to build an object file
recurso.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/heap_espaconave.dir/build.make CMakeFiles/heap_espaconave.dir/recurso.cpp.o
.PHONY : recurso.cpp.o

recurso.i: recurso.cpp.i
.PHONY : recurso.i

# target to preprocess a source file
recurso.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/heap_espaconave.dir/build.make CMakeFiles/heap_espaconave.dir/recurso.cpp.i
.PHONY : recurso.cpp.i

recurso.s: recurso.cpp.s
.PHONY : recurso.s

# target to generate assembly for a file
recurso.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/heap_espaconave.dir/build.make CMakeFiles/heap_espaconave.dir/recurso.cpp.s
.PHONY : recurso.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... run"
	@echo "... heap_espaconave"
	@echo "... espacoNave.o"
	@echo "... espacoNave.i"
	@echo "... espacoNave.s"
	@echo "... heap.o"
	@echo "... heap.i"
	@echo "... heap.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... passageiro.o"
	@echo "... passageiro.i"
	@echo "... passageiro.s"
	@echo "... recurso.o"
	@echo "... recurso.i"
	@echo "... recurso.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

